version: "3.9"

services:
  lambda:
    build:
      context: .
      target: development
    ports:
      - "9000:8080"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./README.md:/app/README.md:ro
      - ./LICENSE:/app/LICENSE:ro
      - ./models:/app/models
    command: ["/usr/local/bin/aws-lambda-rie", "python3", "-m", "awslambdaric", "app.handler.lambda_handler"]